#' Base class for geom_label_timeline
#'
#' @param required_aes the required asethetics for this geom are
#' \enumerate{
#'  \item label a character containing the text of the label
#' }
#' @param default_aes default asthetics for this geom are
#' \enumerate{
#'  \item n_max integer setting the maximum number of labels to display.
#'  If set, will only display the labels of the top n_max earthquakes by magnitude
#' }
#'
#' @seealso [geom_timeline()]
GeomLabelTimeline <- ggplot2::ggproto("GeomLabelTimeline", ggplot2::Geom,
                        required_aes = c("label"),
                        default_aes = c(n_max=5),
                        draw_key = ggplot2::draw_key_point,
                        draw_panel = function(data, panel_scales, coord) {
                          # filter to the top 5 for each country
                          data <- data %>%
                            dplyr::group_by(y) %>%
                            dplyr::top_n(wt=size, n=data$n_max[1])

                          data_trans <- coord$transform(data, panel_scales)

                          data_trans$y0 <- data_trans$y + 0.05


                          text_labels <- grid::textGrob(
                            label = data_trans$label,
                            x=data_trans$x,
                            y=data_trans$y0,
                            just="left",
                            rot=45,
                            check.overlap = TRUE,
                            gp=grid::gpar(fontsize=10)
                          )

                          segments <- grid::segmentsGrob(
                            x0=data_trans$x,
                            x1=data_trans$x,
                            y0=data_trans$y0,
                            y=data_trans$y,
                            default.units="npc"
                          )

                          return(grid::gTree(children=grid::gList(segments, text_labels)))
                        }
                      )


#' Add labels to timeline
#'
#' Add labels to a timeline geom with option to limit to top n largest earthquakes
#'
#' This geom adds labels to the figure generated by [geom_timeline()] and must be used
#' on conjunction with this geom as it inherits several of its aesthetics.
#'
#' @param mapping A set of aesthetic mappings created by \code{aes()}
#' @param data The data to be displayed in this layer
#'
#' @section Aesthetics:
#'
#' The following aesthetics are supported. Position aesthetics are inherited from [geom_timeline()].
#'
#' \itemize{
#'   \item label character with the text of the label
#'   \item n_max optional integer specifying the top number of earthquakes to display
#' }
#'
#' @seealso [geom_timeline()]
#'
#' @examples
#' \dontrun{
#' data <- eq_clean(raw_data)
#'  data %>%
#'   ggplot(aes(x=Year, y=Country, size=Magnitude, fill=Deaths)) +
#'   geom_timeline(alpha=0.5) +
#'   geom_label_timeline(aes(label=label), x_max=5)
#' }
#'
#'
#' @export
geom_label_timeline <- function(
  mapping=NULL,
  data=NULL,
  stat="identity",
  position="identity",
  na.rm=TRUE,
  show.legend=NA,
  inherit.aes=TRUE, ...) {
  ggplot2::layer(
    geom=GeomLabelTimeline,
    mapping=mapping,
    data=data,
    stat=stat,
    position=position,
    show.legend=show.legend,
    inherit.aes = inherit.aes,
    params=list(na.rm=na.rm, ...)
  )
}
